"""
generate_utilities.py — Generate CSS utility classes from the Figma registry.

Reads figma-registry.json and emits CSS utility classes for color, spacing,
and corner tokens. Each utility class references the corresponding CSS custom
property (generated by generate_css), not the raw value — so the two outputs
stay in sync automatically.

Output examples:
  .text-brand-primary   { color: var(--color-brand-primary); }
  .bg-surface-primary   { background-color: var(--color-surface-primary); }
  .border-default       { border-color: var(--color-border-default); }
  .p-base               { padding: var(--spacing-base); }
  .gap-base             { gap: var(--spacing-base); }
  .rounded-base         { border-radius: var(--corner-base); }

The generated file is a supplement — it doesn't replace Tailwind or any
existing utility layer. Import or concat with your other utility files.

CLI:
    python -m figma_primitives generate-utilities --input <registry.json> --output <file>
"""

import sys
import json
import argparse
from pathlib import Path

try:
    from figma_primitives.generate_css import figma_name_to_css, _flatten_registry_variables
except ImportError:
    from generate_css import figma_name_to_css, _flatten_registry_variables


def _short_name(figma_name: str) -> str:
    """
    Derive a short utility-class suffix from a Figma token name.
    color/brand/primary → brand-primary
    spacing/base        → base
    corners/corner-base → base
    """
    parts = figma_name.lower().split("/")
    # Drop the top-level category segment
    rest = parts[1:]
    if not rest:
        return figma_name.lower().replace("/", "-")

    # For corners, strip redundant "corner-" prefix
    name = "-".join(rest).replace(" ", "-")
    if parts[0] == "corners" and name.startswith("corner-"):
        name = name[len("corner-"):]
    return name


def _classify_color(figma_name: str) -> list:
    """
    Determine which utility classes to generate for a color token.
    Returns list of (class_suffix, property).
    """
    n = figma_name.lower()
    classes = []

    if "text" in n or "foreground" in n or "on-" in n:
        classes.append(("text", "color"))
    elif "surface" in n or "background" in n or "bg-" in n or "fill" in n:
        classes.append(("bg", "background-color"))
    elif "border" in n or "stroke" in n or "outline" in n:
        classes.append(("border", "border-color"))
    elif "status-" in n:
        # Status tokens: emit both bg and text variants based on suffix
        if n.endswith("-bg"):
            classes.append(("bg", "background-color"))
        elif n.endswith("-text"):
            classes.append(("text", "color"))
        else:
            classes.append(("bg", "background-color"))
            classes.append(("text", "color"))
    else:
        # Generic color: emit as both text and bg
        classes.append(("text", "color"))
        classes.append(("bg", "background-color"))

    return classes


def generate(registry: dict) -> str:
    """Generate CSS utility classes. Returns CSS string."""
    flat = _flatten_registry_variables(registry)
    meta = registry.get("meta", {})
    file_key = meta.get("fileKey", "unknown")
    scan_date = meta.get("scanDate", "unknown")

    lines = [
        f"/* Generated utility classes — fileKey: {file_key} — scanDate: {scan_date} */",
        "/* Utility classes reference CSS variables from generate-css output. */",
        "/* Do not edit manually. Re-run: python -m figma_primitives generate-utilities */",
        "",
    ]

    # --- Color utilities ---
    color_tokens = [(n, v) for n, v in flat.items() if n.lower().startswith("color/")]
    if color_tokens:
        lines.append("/* Color utilities */")
        for figma_name, _value in sorted(color_tokens, key=lambda x: x[0]):
            css_var = figma_name_to_css(figma_name)
            short = _short_name(figma_name)
            for prefix, prop in _classify_color(figma_name):
                lines.append(f".{prefix}-{short} {{ {prop}: var({css_var}); }}")
        lines.append("")

    # --- Spacing utilities ---
    spacing_tokens = [(n, v) for n, v in flat.items() if n.lower().startswith("spacing/")]
    if spacing_tokens:
        lines.append("/* Spacing utilities */")
        for figma_name, _value in sorted(spacing_tokens, key=lambda x: x[0]):
            css_var = figma_name_to_css(figma_name)
            short = _short_name(figma_name)
            lines.append(f".p-{short}   {{ padding: var({css_var}); }}")
            lines.append(f".px-{short}  {{ padding-left: var({css_var}); padding-right: var({css_var}); }}")
            lines.append(f".py-{short}  {{ padding-top: var({css_var}); padding-bottom: var({css_var}); }}")
            lines.append(f".m-{short}   {{ margin: var({css_var}); }}")
            lines.append(f".gap-{short} {{ gap: var({css_var}); }}")
        lines.append("")

    # --- Corner radius utilities ---
    corner_tokens = [(n, v) for n, v in flat.items() if n.lower().startswith("corners/")]
    if corner_tokens:
        lines.append("/* Corner radius utilities */")
        for figma_name, _value in sorted(corner_tokens, key=lambda x: x[0]):
            css_var = figma_name_to_css(figma_name)
            short = _short_name(figma_name)
            lines.append(f".rounded-{short} {{ border-radius: var({css_var}); }}")
        lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate CSS utility classes from figma-registry.json",
        prog="figma_primitives generate-utilities",
    )
    parser.add_argument("--input", required=True, help="figma-registry.json")
    parser.add_argument("--output", required=True, help="Output CSS file path")
    args = parser.parse_args(argv)

    with open(args.input) as f:
        registry = json.load(f)

    css = generate(registry)
    flat = _flatten_registry_variables(registry)
    print(f"Generated utilities for {len(flat)} variables", file=sys.stderr)

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w") as f:
        f.write(css)
    print(f"Wrote: {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
