"""
prep_bind.py — Port of figma-bind-prep.sh.

Takes Phase 1 and Phase 2 JSON output from figma-bind-variables and generates
ready-to-paste Phase 4a-4d Plugin API scripts with:
  - varDefs pre-filled from Phase 2 validated IDs (cross-referenced against Phase 1)
  - colorMap pre-built from Phase 2 resolved hex values
  - COMPONENTS_PAGE injected from figma-config.json (or flag)

Phase 1 input shape (from Figma figma_execute run):
  {
    "boundCount": N,
    "resolved": {
      "VariableID:x:y": { "name": "color/brand/primary", "type": "COLOR" },
      ...
    }
  }

Phase 2 input shape (from Figma figma_execute run):
  {
    "results": {
      "brandPrimary": {
        "name": "color/brand/primary",
        "type": "COLOR",
        "resolved": { "hex": "#1a2b3c" }
      },
      ...
    },
    "failed": []
  }

Output directory (default /tmp/figma-bind/):
  phase4a-text-fills.js
  phase4b-surface-fills.js
  phase4c-strokes.js
  phase4d-corners.js
  SUMMARY.md

CLI:
    python -m figma_primitives prep-bind --phase1 <file> --phase2 <file> [--config <figma-config.json>] [--out <dir>]
"""

import sys
import json
import os
import argparse
from pathlib import Path


DEFAULT_OUT = "/tmp/figma-bind"


def _load_config(config_path: str | None) -> dict:
    if config_path and Path(config_path).exists():
        with open(config_path) as f:
            return json.load(f)
    # Try current directory convention
    cwd_config = Path.cwd() / ".claude" / "figma-config.json"
    if cwd_config.exists():
        with open(cwd_config) as f:
            return json.load(f)
    return {}


def _build_var_maps(phase1: dict, phase2: dict) -> tuple:
    """
    Returns (var_defs, color_map, corner_map, warnings).
    var_defs:   { camelKey: "VariableID:x:y" }
    color_map:  { hex6 (no #): camelKey }
    corner_map: { radius_value (float): camelKey }
    warnings:   list of string
    """
    p1_resolved = phase1.get("resolved", {})
    results = phase2.get("results", {})
    failed = phase2.get("failed", [])
    warnings = []

    if failed:
        warnings.append(f"{len(failed)} variables failed in Phase 2: {failed}")

    # name → ID lookup from Phase 1
    name_to_id = {v["name"]: k for k, v in p1_resolved.items()}

    var_defs = {}
    color_map = {}
    corner_map = {}

    for key, info in results.items():
        var_name = info.get("name", "")
        resolved = info.get("resolved", {})
        var_id = name_to_id.get(var_name, "")

        if not var_id:
            warnings.append(f"Could not find ID for '{var_name}' (key: {key}) — not in Phase 1 results")
            continue

        var_defs[key] = var_id

        if info.get("type") == "COLOR" and "hex" in resolved:
            hex_val = resolved["hex"].lstrip("#").lower()
            color_map[hex_val] = key
        elif info.get("type") == "FLOAT" and "value" in resolved:
            corner_map[resolved["value"]] = key

    return var_defs, color_map, corner_map, warnings


def _render_js_obj(name: str, d: dict) -> str:
    lines = [f"const {name} = {{"]
    for k, v in sorted(d.items()):
        if isinstance(v, str):
            lines.append(f'  {k}: "{v}",')
        else:
            lines.append(f"  {k}: {v},")
    lines.append("};")
    return "\n".join(lines)


def _page_boilerplate(components_page: str) -> str:
    return f'''\
const COMPONENTS_PAGE = "{components_page}";

const compPage = figma.root.children.find(p => p.name === COMPONENTS_PAGE);
if (!compPage) return {{ error: `Page "${{COMPONENTS_PAGE}}" not found` }};
await figma.setCurrentPageAsync(compPage);'''


def _load_vars_block() -> str:
    return '''\
const V = {};
for (const [k, id] of Object.entries(varDefs)) {
  V[k] = await figma.variables.getVariableByIdAsync(id);
  if (!V[k]) return { error: `Failed to load: ${k}` };
}'''


def _hex_fn() -> str:
    return "function toHex8(c) {\n  return [c.r,c.g,c.b].map(v=>Math.round(v*255).toString(16).padStart(2,'0')).join('');\n}"


def generate_phase4a(var_defs: dict, color_map: dict, components_page: str) -> str:
    return f"""// Phase 4a: Text fills — generated by figma_primitives prep-bind
// Do not edit varDefs or colorMap manually — re-run prep-bind if IDs change.
{_page_boilerplate(components_page)}

{_render_js_obj('varDefs', var_defs)}
{_load_vars_block()}

{_render_js_obj('colorMap', color_map)}

{_hex_fn()}

const bound = [], errors = [];
const allText = compPage.findAll(n => n.type === "TEXT" && !n.id.includes(';'));

for (const node of allText) {{
  if (node.fills === figma.mixed || !Array.isArray(node.fills)) continue;
  let fills = [...node.fills];
  let changed = false;
  for (let i = 0; i < fills.length; i++) {{
    const fill = fills[i];
    if (fill.type !== 'SOLID' || fill.opacity === 0) continue;
    if (node.boundVariables?.fills?.[i]?.id) continue;
    const varKey = colorMap[toHex8(fill.color)];
    if (!varKey) continue;
    try {{
      fills[i] = figma.variables.setBoundVariableForPaint(fills[i], 'color', V[varKey]);
      changed = true;
      bound.push({{ varKey, hex: toHex8(fill.color) }});
    }} catch (e) {{ errors.push({{ nodeId: node.id, err: e.message.slice(0,80) }}); }}
  }}
  if (changed) {{
    try {{ node.fills = fills; }} catch (e) {{ errors.push({{ phase: 'assign', err: e.message.slice(0,80) }}); }}
  }}
}}

const tally = {{}};
for (const b of bound) tally[b.varKey] = (tally[b.varKey]||0)+1;
return {{ boundTotal: bound.length, tally, errorCount: errors.length, errors: errors.slice(0,5) }};
"""


def generate_phase4b(var_defs: dict, color_map: dict, components_page: str) -> str:
    return f"""// Phase 4b: Surface fills — generated by figma_primitives prep-bind
{_page_boilerplate(components_page)}

{_render_js_obj('varDefs', var_defs)}
{_load_vars_block()}

{_render_js_obj('colorMap', color_map)}

{_hex_fn()}

const SURFACE_TYPES = new Set(["FRAME", "RECTANGLE", "ELLIPSE", "COMPONENT"]);
const bound = [], errors = [];
const candidates = compPage.findAll(n =>
  SURFACE_TYPES.has(n.type) && !n.id.includes(';') && !n.isMask
);

for (const node of candidates) {{
  if (node.fills === figma.mixed || !Array.isArray(node.fills)) continue;
  let fills = [...node.fills];
  let changed = false;
  for (let i = 0; i < fills.length; i++) {{
    const fill = fills[i];
    if (fill.type !== 'SOLID') continue;
    if (fill.color.r > 0.99 && fill.color.g > 0.99 && fill.color.b > 0.99 && (fill.opacity ?? 1) < 0.99) continue;
    if (node.boundVariables?.fills?.[i]?.id) continue;
    const varKey = colorMap[toHex8(fill.color)];
    if (!varKey) continue;
    try {{
      fills[i] = figma.variables.setBoundVariableForPaint(fills[i], 'color', V[varKey]);
      changed = true;
      bound.push({{ varKey, hex: toHex8(fill.color) }});
    }} catch (e) {{ errors.push({{ nodeId: node.id, err: e.message.slice(0,80) }}); }}
  }}
  if (changed) {{
    try {{ node.fills = fills; }} catch (e) {{ errors.push({{ phase: 'assign', err: e.message.slice(0,80) }}); }}
  }}
}}

const tally = {{}};
for (const b of bound) tally[b.varKey] = (tally[b.varKey]||0)+1;
return {{ boundTotal: bound.length, tally, errorCount: errors.length, errors: errors.slice(0,5) }};
"""


def generate_phase4c(var_defs: dict, color_map: dict, components_page: str) -> str:
    return f"""// Phase 4c: Strokes — generated by figma_primitives prep-bind
{_page_boilerplate(components_page)}

{_render_js_obj('varDefs', var_defs)}
{_load_vars_block()}

{_render_js_obj('colorMap', color_map)}

{_hex_fn()}

const bound = [], errors = [];
const candidates = compPage.findAll(n => 'strokes' in n && !n.id.includes(';'));

for (const node of candidates) {{
  if (!Array.isArray(node.strokes) || node.strokes === figma.mixed) continue;
  let strokes = [...node.strokes];
  let changed = false;
  for (let i = 0; i < strokes.length; i++) {{
    const stroke = strokes[i];
    if (stroke.type !== 'SOLID') continue;
    if (node.boundVariables?.strokes?.[i]?.id) continue;
    const varKey = colorMap[toHex8(stroke.color)];
    if (!varKey) continue;
    try {{
      strokes[i] = figma.variables.setBoundVariableForPaint(strokes[i], 'color', V[varKey]);
      changed = true;
      bound.push({{ varKey, hex: toHex8(stroke.color) }});
    }} catch (e) {{ errors.push({{ nodeId: node.id, err: e.message.slice(0,80) }}); }}
  }}
  if (changed) {{
    try {{ node.strokes = strokes; }} catch (e) {{ errors.push({{ phase: 'assign', err: e.message.slice(0,80) }}); }}
  }}
}}

const tally = {{}};
for (const b of bound) tally[b.varKey] = (tally[b.varKey]||0)+1;
return {{ boundTotal: bound.length, tally, errorCount: errors.length, errors: errors.slice(0,5) }};
"""


def generate_phase4d(var_defs: dict, corner_map: dict, components_page: str) -> str:
    # Build corner-only varDefs
    corner_var_defs = {k: v for k, v in var_defs.items() if k.startswith("corner")}
    if not corner_var_defs:
        corner_var_defs = var_defs

    # Build getCornerVar() body from corner_map
    corner_checks = []
    for val, key in sorted(corner_map.items(), key=lambda x: float(x[0]) if isinstance(x[0], (int, float)) else 999):
        corner_checks.append(f"  if (Math.abs(val - {val}) < 0.5) return '{key}';")
    # Always include the >10000 full-radius guard
    if not any("10000" in c for c in corner_checks):
        corner_checks.append("  if (val > 10000) return 'cornerFull';")
    corner_checks_str = "\n".join(corner_checks) if corner_checks else "  return null;"

    return f"""// Phase 4d: Corner radii — generated by figma_primitives prep-bind
{_page_boilerplate(components_page)}

{_render_js_obj('varDefs', corner_var_defs)}
{_load_vars_block()}

function getCornerVar(val) {{
{corner_checks_str}
  return null;
}}

const bound = [], errors = [];
const candidates = compPage.findAll(n => 'cornerRadius' in n && !n.id.includes(';'));

for (const node of candidates) {{
  if (node.cornerRadius === figma.mixed) continue;
  if (typeof node.cornerRadius !== 'number' || node.cornerRadius <= 0) continue;
  if (node.boundVariables?.cornerRadius) continue;
  const varKey = getCornerVar(node.cornerRadius);
  if (!varKey || !V[varKey]) continue;
  try {{
    node.setBoundVariable('cornerRadius', V[varKey]);
    bound.push({{ varKey, value: node.cornerRadius }});
  }} catch (e) {{ errors.push({{ nodeId: node.id, err: e.message.slice(0,80) }}); }}
}}

const tally = {{}};
for (const b of bound) tally[b.varKey] = (tally[b.varKey]||0)+1;
return {{ boundTotal: bound.length, tally, errorCount: errors.length, errors: errors.slice(0,5) }};
"""


def generate_summary(var_defs: dict, color_map: dict, corner_map: dict,
                     results: dict, failed: list, components_page: str,
                     phase1_path: str, phase2_path: str, out_dir: str) -> str:
    lines = [
        "# figma-bind-prep output",
        "",
        f"Generated from: {Path(phase1_path).name} + {Path(phase2_path).name}",
        f"COMPONENTS_PAGE: {components_page}",
        "",
        f"## Variable definitions ({len(var_defs)} resolved)",
    ]
    for k, v in var_defs.items():
        info = results.get(k, {})
        resolved = info.get("resolved", {})
        hex_str = resolved.get("hex", resolved.get("value", "?"))
        lines.append(f"  - {k}: {info.get('name', k)} = {hex_str}")

    if failed:
        lines += ["", f"## Failed ({len(failed)})", *[f"  - {f}" for f in failed]]

    lines += [
        "",
        "## Color map",
        *[f"  #{h} → {k}" for h, k in sorted(color_map.items())],
        "",
        "## Scripts generated",
        f"  - {out_dir}/phase4a-text-fills.js",
        f"  - {out_dir}/phase4b-surface-fills.js",
        f"  - {out_dir}/phase4c-strokes.js",
        f"  - {out_dir}/phase4d-corners.js",
    ]
    return "\n".join(lines) + "\n"


def run(phase1_path: str, phase2_path: str, config_path: str | None, out_dir: str):
    with open(phase1_path) as f:
        phase1 = json.load(f)
    with open(phase2_path) as f:
        phase2 = json.load(f)

    config = _load_config(config_path)
    components_page = config.get("componentsPage", "Components")

    var_defs, color_map, corner_map, warnings = _build_var_maps(phase1, phase2)

    for w in warnings:
        print(f"WARNING: {w}", file=sys.stderr)

    results = phase2.get("results", {})
    failed = phase2.get("failed", [])

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    scripts = {
        "phase4a-text-fills.js": generate_phase4a(var_defs, color_map, components_page),
        "phase4b-surface-fills.js": generate_phase4b(var_defs, color_map, components_page),
        "phase4c-strokes.js": generate_phase4c(var_defs, color_map, components_page),
        "phase4d-corners.js": generate_phase4d(var_defs, corner_map, components_page),
    }
    for name, content in scripts.items():
        (out / name).write_text(content)

    summary = generate_summary(
        var_defs, color_map, corner_map, results, failed,
        components_page, phase1_path, phase2_path, out_dir,
    )
    (out / "SUMMARY.md").write_text(summary)

    print(f"COMPONENTS_PAGE: {components_page}", file=sys.stderr)
    print(f"Variables resolved: {len(var_defs)}", file=sys.stderr)
    print(f"Color map entries: {len(color_map)}", file=sys.stderr)
    print(f"\nGenerated scripts in {out_dir}/", file=sys.stderr)
    for name in scripts:
        print(f"  {name}", file=sys.stderr)
    print("  SUMMARY.md", file=sys.stderr)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate Phase 4a-4d bind scripts from Phase 1+2 JSON",
        prog="figma_primitives prep-bind",
    )
    parser.add_argument("--phase1", required=True, help="Phase 1 JSON (variable discovery)")
    parser.add_argument("--phase2", required=True, help="Phase 2 JSON (variable validation)")
    parser.add_argument("--config", default=None, help="figma-config.json path (optional)")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"Output directory (default: {DEFAULT_OUT})")
    args = parser.parse_args(argv)

    run(args.phase1, args.phase2, args.config, args.out)


if __name__ == "__main__":
    main()
