"""
prep_idmap.py — Port of figma-idmap-inject.sh.

Takes Phase 2 output from figma-swap-library-to-local (the idMap JSON)
and generates a ready-to-paste Phase 3 Plugin API script with idMap pre-filled.

Phase 2 input shape (save from Figma console):
  { "count": 42, "idMap": { "Icons::Icon=Arrow": "123:456", ... } }

Output directory (default /tmp/figma-swap/):
  phase3-swap.js    — paste into Figma console
  SUMMARY.md

CLI:
    python -m figma_primitives prep-idmap --phase2 <file> --node-id <id> [--out <dir>]

The node-id is the Figma node ID of the container to swap within.
URL format (1234-5678) is automatically converted to Figma format (1234:5678).
"""

import sys
import json
import argparse
from pathlib import Path


DEFAULT_OUT = "/tmp/figma-swap"


def _normalize_node_id(raw: str) -> str:
    """Convert URL format 1234-5678 to Figma format 1234:5678."""
    return raw.replace("-", ":", 1) if raw.count("-") == 1 and ":" not in raw else raw


def _render_id_map_js(id_map: dict) -> str:
    lines = ["const idMap = {"]
    for key in sorted(id_map):
        escaped_key = key.replace('"', '\\"')
        node_id = id_map[key]
        lines.append(f'  "{escaped_key}": "{node_id}",')
    lines.append("};")
    return "\n".join(lines)


def generate_phase3(id_map: dict, node_id: str) -> str:
    id_map_js = _render_id_map_js(id_map)
    return f"""// Phase 3: Parent-down swap — generated by figma_primitives prep-idmap
// idMap sourced from Phase 2 output. Do not edit IDs manually — re-run if components change.

{id_map_js}

let targetNode = null;
for (const page of figma.root.children) {{
  await figma.setCurrentPageAsync(page);
  targetNode = await figma.getNodeByIdAsync("{node_id}");
  if (targetNode) break;
}}
if (!targetNode) return {{ error: "Node not found: {node_id}" }};

const instances = targetNode.findAll(n => n.type === "INSTANCE");

// Identify all remote instances
const remoteInstances = [], remoteInstanceIds = new Set();
for (const inst of instances) {{
  let mc;
  try {{ mc = await inst.getMainComponentAsync(); }} catch (e) {{ continue; }}
  if (mc?.remote) {{ remoteInstances.push({{ inst, mc }}); remoteInstanceIds.add(inst.id); }}
}}

// Filter: outermost only — skip children whose ancestor is also being swapped
function hasRemoteAncestor(node) {{
  let cur = node.parent;
  while (cur && cur.type !== "PAGE" && cur.type !== "SECTION") {{
    if (remoteInstanceIds.has(cur.id)) return true;
    cur = cur.parent;
  }}
  return false;
}}
const topLevel = remoteInstances.filter(({{ inst }}) => !hasRemoteAncestor(inst));

// Swap
const swapped = [], skipped = [], errors = [], mutatedNodeIds = [];
for (const {{ inst, mc }} of topLevel) {{
  const setName = (mc.parent?.type === "COMPONENT_SET") ? mc.parent.name : null;
  const lookupKey = setName ? `${{setName}}::${{mc.name}}` : `__standalone::${{mc.name}}`;
  const localId = idMap[lookupKey];
  if (!localId) {{ skipped.push({{ componentName: mc.name, setName }}); continue; }}

  const localComponent = await figma.getNodeByIdAsync(localId);
  if (!localComponent) {{ errors.push({{ componentName: mc.name, error: "not found" }}); continue; }}

  try {{
    inst.swapComponent(localComponent);
    swapped.push({{ componentName: mc.name, setName }});
    mutatedNodeIds.push(inst.id);
  }} catch (e) {{ errors.push({{ componentName: mc.name, error: e.message }}); }}
}}

return {{
  swappedCount: swapped.length,
  skippedCount: skipped.length,
  errorCount: errors.length,
  skipped,
  errors,
  mutatedNodeIds,
}};
"""


def generate_summary(id_map: dict, node_id: str, phase2_path: str, out_dir: str) -> str:
    lines = [
        "# figma-idmap-inject output",
        "",
        f"Generated from: {Path(phase2_path).name}",
        f"Target node ID: {node_id}",
        f"idMap entries: {len(id_map)}",
        "",
        "## Mapped components",
    ]
    for key in sorted(id_map):
        lines.append(f"  - {key} → {id_map[key]}")

    lines += [
        "",
        "## Next step",
        "1. Open Figma console (Plugins → Development → Open Console)",
        f"2. Paste contents of {out_dir}/phase3-swap.js",
        "3. Review skipped[] — confirm any non-obvious mappings with user",
        "4. Re-run Phase 1 scan to verify remoteCount dropped",
    ]
    return "\n".join(lines) + "\n"


def run(phase2_path: str, raw_node_id: str, out_dir: str):
    with open(phase2_path) as f:
        phase2 = json.load(f)

    id_map = phase2.get("idMap", {})
    if not id_map:
        print("ERROR: idMap is empty in Phase 2 output", file=sys.stderr)
        sys.exit(1)

    node_id = _normalize_node_id(raw_node_id)
    print(f"idMap entries: {len(id_map)}", file=sys.stderr)
    print(f"Target node:   {node_id}", file=sys.stderr)

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    script = generate_phase3(id_map, node_id)
    (out / "phase3-swap.js").write_text(script)

    summary = generate_summary(id_map, node_id, phase2_path, out_dir)
    (out / "SUMMARY.md").write_text(summary)

    print(f"\nGenerated:", file=sys.stderr)
    print(f"  {out_dir}/phase3-swap.js", file=sys.stderr)
    print(f"  {out_dir}/SUMMARY.md", file=sys.stderr)
    print(f"\nPaste phase3-swap.js into the Figma console to run the swap.", file=sys.stderr)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Generate Phase 3 swap script from Phase 2 idMap JSON",
        prog="figma_primitives prep-idmap",
    )
    parser.add_argument("--phase2", required=True, help="Phase 2 JSON (idMap output from Figma)")
    parser.add_argument("--node-id", required=True, help="Target Figma node ID (URL or Figma format)")
    parser.add_argument("--out", default=DEFAULT_OUT, help=f"Output directory (default: {DEFAULT_OUT})")
    args = parser.parse_args(argv)

    run(args.phase2, args.node_id, args.out)


if __name__ == "__main__":
    main()
